// Curated, realistic Indian hackathon seed data.
// Used for instant aha-moment while live scrapers are wired in.
import { v4 as uuid } from 'uuid';

const now = new Date();
const daysFromNow = (d) => {
  const x = new Date(now);
  x.setDate(x.getDate() + d);
  return x.toISOString();
};

const H = (o) => ({
  id: uuid(),
  saves: Math.floor(Math.random() * 800) + 20,
  createdAt: new Date().toISOString(),
  studentOnly: false,
  beginnerFriendly: false,
  soloAllowed: true,
  teamAllowed: true,
  imageUrl: null,
  ...o,
});

export const SEED_HACKATHONS = [
  H({
    name: 'Smart India Hackathon 2025',
    organizer: 'Ministry of Education, AICTE',
    description: 'The flagship national-level hackathon by MoE solving real-world problems across 17 themes.',
    prizePool: 10000000,
    registrationDeadline: daysFromNow(12),
    startDate: daysFromNow(28),
    endDate: daysFromNow(30),
    mode: 'offline',
    location: 'Multiple Nodal Centres (Pan-India)',
    teamSize: { min: 6, max: 6 },
    themes: ['Open Innovation', 'AI', 'Blockchain', 'Cybersecurity'],
    difficulty: 'Intermediate',
    registrationLink: 'https://www.sih.gov.in',
    source: 'Unstop',
    studentOnly: true,
    beginnerFriendly: true,
  }),
  H({
    name: 'HackWithIndia AI 2025',
    organizer: 'Devfolio x AWS',
    description: 'Build the next generation of GenAI apps. Cloud credits, GPU compute and AWS Bedrock mentorship.',
    prizePool: 1500000,
    registrationDeadline: daysFromNow(5),
    startDate: daysFromNow(14),
    endDate: daysFromNow(16),
    mode: 'hybrid',
    location: 'Bengaluru + Online',
    teamSize: { min: 1, max: 4 },
    themes: ['AI', 'Machine Learning', 'Open Innovation'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'ETHIndia 2025',
    organizer: 'Devfolio',
    description: "India's largest Ethereum hackathon. Build on-chain. ₹50L+ in bounties from top web3 sponsors.",
    prizePool: 5000000,
    registrationDeadline: daysFromNow(25),
    startDate: daysFromNow(45),
    endDate: daysFromNow(47),
    mode: 'offline',
    location: 'Bengaluru',
    teamSize: { min: 1, max: 4 },
    themes: ['Blockchain', 'Web Development'],
    difficulty: 'Advanced',
    registrationLink: 'https://ethindia.co',
    source: 'Devfolio',
  }),
  H({
    name: 'CodeKshetra 2.0',
    organizer: 'IGDTUW',
    description: 'A 36-hour offline women-led hackathon focused on social impact tech.',
    prizePool: 300000,
    registrationDeadline: daysFromNow(8),
    startDate: daysFromNow(20),
    endDate: daysFromNow(22),
    mode: 'offline',
    location: 'Delhi NCR',
    teamSize: { min: 2, max: 4 },
    themes: ['Open Innovation', 'Web Development', 'AI'],
    difficulty: 'Beginner',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
    studentOnly: true,
    beginnerFriendly: true,
  }),
  H({
    name: 'Hack The Mountains 5.0',
    organizer: 'HTM Community',
    description: 'A 48-hour international online hackathon. Open theme with sponsor tracks.',
    prizePool: 500000,
    registrationDeadline: daysFromNow(3),
    startDate: daysFromNow(10),
    endDate: daysFromNow(12),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['Open Innovation', 'AI', 'Web Development', 'Mobile Development'],
    difficulty: 'Beginner',
    registrationLink: 'https://devpost.com',
    source: 'Devpost',
    beginnerFriendly: true,
  }),
  H({
    name: 'TechGig Code Gladiators 2025',
    organizer: 'TechGig',
    description: "India's largest coding championship. Algorithmic + project rounds with corporate hiring.",
    prizePool: 5000000,
    registrationDeadline: daysFromNow(18),
    startDate: daysFromNow(35),
    endDate: daysFromNow(70),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 1 },
    themes: ['Open Innovation', 'AI', 'Web Development'],
    difficulty: 'Advanced',
    registrationLink: 'https://www.techgig.com',
    source: 'HackerEarth',
  }),
  H({
    name: 'Flipkart GRiD 7.0',
    organizer: 'Flipkart',
    description: "Flipkart's flagship engineering challenge with PPO opportunities.",
    prizePool: 2500000,
    registrationDeadline: daysFromNow(15),
    startDate: daysFromNow(22),
    endDate: daysFromNow(60),
    mode: 'hybrid',
    location: 'Bengaluru + Online',
    teamSize: { min: 1, max: 3 },
    themes: ['AI', 'Machine Learning', 'Web Development', 'Mobile Development'],
    difficulty: 'Advanced',
    registrationLink: 'https://unstop.com/flipkart-grid',
    source: 'Unstop',
    studentOnly: true,
  }),
  H({
    name: 'Amazon ML Challenge 2025',
    organizer: 'Amazon',
    description: 'Solve real-world ML problems on Amazon-scale datasets. Top performers get fast-tracked interviews.',
    prizePool: 1000000,
    registrationDeadline: daysFromNow(7),
    startDate: daysFromNow(14),
    endDate: daysFromNow(17),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 3 },
    themes: ['Machine Learning', 'AI'],
    difficulty: 'Advanced',
    registrationLink: 'https://unstop.com/amazon',
    source: 'Unstop',
    studentOnly: true,
  }),
  H({
    name: 'Hack Bengaluru 2025',
    organizer: 'Karnataka Govt + NASSCOM',
    description: 'A city-wide civic-tech hackathon. Solve problems for BBMP and BMTC.',
    prizePool: 800000,
    registrationDeadline: daysFromNow(20),
    startDate: daysFromNow(40),
    endDate: daysFromNow(42),
    mode: 'offline',
    location: 'Bengaluru',
    teamSize: { min: 2, max: 5 },
    themes: ['Open Innovation', 'AI', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'CyberShield CTF 2025',
    organizer: 'NullCon',
    description: 'A 24-hour capture-the-flag challenge for security researchers and students.',
    prizePool: 400000,
    registrationDeadline: daysFromNow(2),
    startDate: daysFromNow(9),
    endDate: daysFromNow(10),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 3 },
    themes: ['Cybersecurity'],
    difficulty: 'Advanced',
    registrationLink: 'https://hackerearth.com',
    source: 'HackerEarth',
  }),
  H({
    name: 'Reskilll Web3 Buidlathon',
    organizer: 'Reskilll x Polygon',
    description: "Build dApps on Polygon. Open to students and devs across India.",
    prizePool: 700000,
    registrationDeadline: daysFromNow(11),
    startDate: daysFromNow(25),
    endDate: daysFromNow(27),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['Blockchain', 'Web Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://reskilll.com',
    source: 'Reskilll',
  }),
  H({
    name: 'AR/VR India Jam',
    organizer: 'Meta x XR India',
    description: 'Build immersive AR/VR experiences. Meta Quest headsets for top 10 teams.',
    prizePool: 600000,
    registrationDeadline: daysFromNow(16),
    startDate: daysFromNow(30),
    endDate: daysFromNow(32),
    mode: 'hybrid',
    location: 'Hyderabad + Online',
    teamSize: { min: 2, max: 4 },
    themes: ['AR/VR'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'Microsoft Imagine Cup India',
    organizer: 'Microsoft',
    description: "World's premier student technology competition. Use Azure to build for social good.",
    prizePool: 2000000,
    registrationDeadline: daysFromNow(22),
    startDate: daysFromNow(45),
    endDate: daysFromNow(46),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['AI', 'Open Innovation', 'Machine Learning'],
    difficulty: 'Intermediate',
    registrationLink: 'https://imaginecup.microsoft.com',
    source: 'Devpost',
    studentOnly: true,
  }),
  H({
    name: 'IIT Bombay Techfest Hackathon',
    organizer: 'IIT Bombay',
    description: 'Asia\'s largest college-tech-fest hackathon. International judges + corporate sponsors.',
    prizePool: 1500000,
    registrationDeadline: daysFromNow(30),
    startDate: daysFromNow(55),
    endDate: daysFromNow(57),
    mode: 'offline',
    location: 'Mumbai',
    teamSize: { min: 2, max: 4 },
    themes: ['AI', 'Machine Learning', 'Open Innovation', 'Blockchain'],
    difficulty: 'Advanced',
    registrationLink: 'https://techfest.org',
    source: 'Unstop',
  }),
  H({
    name: 'Code For Good - JPMC',
    organizer: 'JPMorgan Chase',
    description: '24-hour hackathon to build tech for NGOs. PPO opportunities for top performers.',
    prizePool: 500000,
    registrationDeadline: daysFromNow(4),
    startDate: daysFromNow(18),
    endDate: daysFromNow(19),
    mode: 'offline',
    location: 'Bengaluru',
    teamSize: { min: 4, max: 5 },
    themes: ['Web Development', 'Open Innovation', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://unstop.com/jpmc',
    source: 'Unstop',
    studentOnly: true,
  }),
  H({
    name: 'HackJaipur 2025',
    organizer: 'JECRC + MLH India',
    description: 'Rajasthan\'s biggest student hackathon. 36 hours of building + workshops.',
    prizePool: 350000,
    registrationDeadline: daysFromNow(14),
    startDate: daysFromNow(28),
    endDate: daysFromNow(30),
    mode: 'offline',
    location: 'Jaipur',
    teamSize: { min: 2, max: 4 },
    themes: ['Web Development', 'Mobile Development', 'AI', 'Open Innovation'],
    difficulty: 'Beginner',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
    studentOnly: true,
    beginnerFriendly: true,
  }),
  H({
    name: 'Tata Crucible Campus Quiz + Hack',
    organizer: 'Tata Group',
    description: "India's most prestigious campus quiz, now with a hackathon track.",
    prizePool: 1000000,
    registrationDeadline: daysFromNow(9),
    startDate: daysFromNow(20),
    endDate: daysFromNow(50),
    mode: 'hybrid',
    location: 'Pan-India',
    teamSize: { min: 2, max: 2 },
    themes: ['Open Innovation'],
    difficulty: 'Intermediate',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
    studentOnly: true,
  }),
  H({
    name: 'FinTech Hack India 2025',
    organizer: 'NPCI x RBI Innovation Hub',
    description: 'Build the future of UPI, lending and capital markets.',
    prizePool: 2500000,
    registrationDeadline: daysFromNow(17),
    startDate: daysFromNow(35),
    endDate: daysFromNow(37),
    mode: 'hybrid',
    location: 'Mumbai + Online',
    teamSize: { min: 2, max: 5 },
    themes: ['Blockchain', 'AI', 'Web Development'],
    difficulty: 'Advanced',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'GirlScript Summer of Code',
    organizer: 'GirlScript Foundation',
    description: '3-month open source program with prize money + swag + LoRs.',
    prizePool: 200000,
    registrationDeadline: daysFromNow(6),
    startDate: daysFromNow(20),
    endDate: daysFromNow(110),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 1 },
    themes: ['Web Development', 'Mobile Development', 'AI', 'Open Innovation'],
    difficulty: 'Beginner',
    registrationLink: 'https://gssoc.girlscript.tech',
    source: 'Devpost',
    beginnerFriendly: true,
  }),
  H({
    name: 'NASA Space Apps - Bengaluru',
    organizer: 'NASA + Spacekidz India',
    description: "NASA's global hackathon with space-themed problems. Local node at Bengaluru.",
    prizePool: 400000,
    registrationDeadline: daysFromNow(19),
    startDate: daysFromNow(38),
    endDate: daysFromNow(40),
    mode: 'offline',
    location: 'Bengaluru',
    teamSize: { min: 1, max: 6 },
    themes: ['AI', 'Open Innovation', 'Machine Learning'],
    difficulty: 'Intermediate',
    registrationLink: 'https://spaceappschallenge.org',
    source: 'Devpost',
  }),
  H({
    name: 'Lablab.ai GenAI Hackathon',
    organizer: 'lablab.ai',
    description: '72-hour global GenAI hackathon with OpenAI, Anthropic and Mistral sponsors.',
    prizePool: 800000,
    registrationDeadline: daysFromNow(10),
    startDate: daysFromNow(20),
    endDate: daysFromNow(23),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 5 },
    themes: ['AI', 'Machine Learning'],
    difficulty: 'Intermediate',
    registrationLink: 'https://lablab.ai',
    source: 'Devpost',
  }),
  H({
    name: 'Hack-N-Pitch Delhi',
    organizer: 'IIT Delhi E-Cell',
    description: 'Idea-to-prototype hackathon with VC pitch finale.',
    prizePool: 600000,
    registrationDeadline: daysFromNow(13),
    startDate: daysFromNow(27),
    endDate: daysFromNow(28),
    mode: 'offline',
    location: 'Delhi NCR',
    teamSize: { min: 2, max: 4 },
    themes: ['Open Innovation', 'AI', 'Web Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'BuildSpace Nights & Weekends India',
    organizer: 'buildspace',
    description: '6-week build sprint. Ship a project, win cash and a trip to SF.',
    prizePool: 700000,
    registrationDeadline: daysFromNow(21),
    startDate: daysFromNow(35),
    endDate: daysFromNow(80),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 1 },
    themes: ['AI', 'Web Development', 'Mobile Development', 'Open Innovation'],
    difficulty: 'Intermediate',
    registrationLink: 'https://buildspace.so',
    source: 'Devpost',
  }),
  H({
    name: 'Hack The North - IITM',
    organizer: 'IIT Madras Shaastra',
    description: 'Flagship hackathon of Shaastra. 36-hours of intense problem solving.',
    prizePool: 500000,
    registrationDeadline: daysFromNow(26),
    startDate: daysFromNow(50),
    endDate: daysFromNow(52),
    mode: 'offline',
    location: 'Chennai',
    teamSize: { min: 3, max: 4 },
    themes: ['AI', 'Machine Learning', 'Open Innovation'],
    difficulty: 'Advanced',
    registrationLink: 'https://shaastra.org',
    source: 'Unstop',
    studentOnly: true,
  }),
  H({
    name: 'Mobile Hack Pune',
    organizer: 'Google Developers Pune',
    description: 'Build Android apps with Jetpack Compose. Direct mentorship from Google engineers.',
    prizePool: 250000,
    registrationDeadline: daysFromNow(8),
    startDate: daysFromNow(18),
    endDate: daysFromNow(19),
    mode: 'offline',
    location: 'Pune',
    teamSize: { min: 1, max: 3 },
    themes: ['Mobile Development'],
    difficulty: 'Beginner',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
    beginnerFriendly: true,
  }),
  H({
    name: 'OpenAI Devday India Hack',
    organizer: 'OpenAI Community India',
    description: 'Build with the latest OpenAI APIs. Demo at OpenAI Devday India.',
    prizePool: 900000,
    registrationDeadline: daysFromNow(1),
    startDate: daysFromNow(7),
    endDate: daysFromNow(9),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['AI', 'Machine Learning'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devpost.com',
    source: 'Devpost',
  }),
  H({
    name: 'HackerEarth Innovation Challenge',
    organizer: 'HackerEarth',
    description: '1-week ML innovation challenge with corporate sponsor data.',
    prizePool: 300000,
    registrationDeadline: daysFromNow(5),
    startDate: daysFromNow(12),
    endDate: daysFromNow(19),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 1 },
    themes: ['Machine Learning', 'AI'],
    difficulty: 'Intermediate',
    registrationLink: 'https://hackerearth.com',
    source: 'HackerEarth',
  }),
  H({
    name: 'Polygon Guild Bengaluru Hack',
    organizer: 'Polygon Labs',
    description: 'Web3 hackathon focused on zkEVM and PoS. Local + remote tracks.',
    prizePool: 1200000,
    registrationDeadline: daysFromNow(23),
    startDate: daysFromNow(45),
    endDate: daysFromNow(47),
    mode: 'hybrid',
    location: 'Bengaluru + Online',
    teamSize: { min: 1, max: 4 },
    themes: ['Blockchain', 'Web Development'],
    difficulty: 'Advanced',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'Design For India - UX Hack',
    organizer: 'NID + Adobe',
    description: 'A design-led hackathon for product designers and PMs. Build for Bharat.',
    prizePool: 250000,
    registrationDeadline: daysFromNow(14),
    startDate: daysFromNow(30),
    endDate: daysFromNow(31),
    mode: 'hybrid',
    location: 'Ahmedabad + Online',
    teamSize: { min: 1, max: 3 },
    themes: ['Open Innovation'],
    difficulty: 'Beginner',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
    beginnerFriendly: true,
  }),
  H({
    name: 'Healthcare AI India Hack',
    organizer: 'AIIMS x NITI Aayog',
    description: 'Build AI tools for diagnostics, triage and patient care. Access to anonymised hospital datasets.',
    prizePool: 1800000,
    registrationDeadline: daysFromNow(24),
    startDate: daysFromNow(48),
    endDate: daysFromNow(50),
    mode: 'offline',
    location: 'Delhi NCR',
    teamSize: { min: 2, max: 5 },
    themes: ['AI', 'Machine Learning'],
    difficulty: 'Advanced',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'Hack4Bharat',
    organizer: 'Reskilll x MeitY',
    description: 'Solve grassroots problems in agri, mobility and education using AI + cloud.',
    prizePool: 1100000,
    registrationDeadline: daysFromNow(11),
    startDate: daysFromNow(25),
    endDate: daysFromNow(27),
    mode: 'hybrid',
    location: 'Pan-India + Online',
    teamSize: { min: 2, max: 5 },
    themes: ['Open Innovation', 'AI', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://reskilll.com',
    source: 'Reskilll',
  }),
  H({
    name: 'GameDev Jam India',
    organizer: 'Unity India',
    description: '72-hour game jam on Unity. Theme revealed at start.',
    prizePool: 200000,
    registrationDeadline: daysFromNow(7),
    startDate: daysFromNow(15),
    endDate: daysFromNow(18),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['AR/VR', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://itch.io',
    source: 'Devpost',
  }),
  H({
    name: 'IoT Smart Cities Hack',
    organizer: 'TCS Research',
    description: 'Build IoT solutions for smart cities. Hardware kits provided.',
    prizePool: 700000,
    registrationDeadline: daysFromNow(20),
    startDate: daysFromNow(40),
    endDate: daysFromNow(43),
    mode: 'offline',
    location: 'Hyderabad',
    teamSize: { min: 3, max: 5 },
    themes: ['Open Innovation', 'AI'],
    difficulty: 'Advanced',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'Hacks For Good - Kolkata',
    organizer: 'CSI Kolkata Chapter',
    description: 'Social impact hackathon with NGO partnerships.',
    prizePool: 150000,
    registrationDeadline: daysFromNow(15),
    startDate: daysFromNow(30),
    endDate: daysFromNow(31),
    mode: 'offline',
    location: 'Kolkata',
    teamSize: { min: 2, max: 4 },
    themes: ['Open Innovation', 'Web Development'],
    difficulty: 'Beginner',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
    beginnerFriendly: true,
    studentOnly: true,
  }),
  H({
    name: 'Quantum India Hack',
    organizer: 'IISc x IBM Quantum',
    description: 'Hack on quantum algorithms using Qiskit. Access to real IBM Quantum hardware.',
    prizePool: 500000,
    registrationDeadline: daysFromNow(28),
    startDate: daysFromNow(55),
    endDate: daysFromNow(56),
    mode: 'hybrid',
    location: 'Bengaluru + Online',
    teamSize: { min: 1, max: 3 },
    themes: ['AI', 'Open Innovation'],
    difficulty: 'Advanced',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'EdTech Innovation Hack',
    organizer: 'BYJU\'S + UpGrad',
    description: 'Reimagine learning. Build AI tutors, gamified courses and student tools.',
    prizePool: 800000,
    registrationDeadline: daysFromNow(12),
    startDate: daysFromNow(28),
    endDate: daysFromNow(30),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['AI', 'Web Development', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://unstop.com',
    source: 'Unstop',
  }),
  H({
    name: 'Hack Goa - Beachside Edition',
    organizer: 'Goa Tech Community',
    description: '48-hour beachside hackathon. Build by day, party by night.',
    prizePool: 350000,
    registrationDeadline: daysFromNow(35),
    startDate: daysFromNow(60),
    endDate: daysFromNow(62),
    mode: 'offline',
    location: 'Goa',
    teamSize: { min: 2, max: 4 },
    themes: ['Open Innovation', 'Web Development', 'AI'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'Climate Hack India',
    organizer: 'Climate.AI x IIT Kanpur',
    description: 'Build ML models for climate forecasting and carbon accounting.',
    prizePool: 600000,
    registrationDeadline: daysFromNow(6),
    startDate: daysFromNow(15),
    endDate: daysFromNow(17),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 4 },
    themes: ['Machine Learning', 'AI', 'Open Innovation'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devpost.com',
    source: 'Devpost',
  }),
  H({
    name: 'StackOverflow x Razorpay DevHack',
    organizer: 'Razorpay',
    description: 'Build developer tools and payment integrations. ₹15L in cash + Razorpay credits.',
    prizePool: 1500000,
    registrationDeadline: daysFromNow(17),
    startDate: daysFromNow(33),
    endDate: daysFromNow(35),
    mode: 'hybrid',
    location: 'Bengaluru + Online',
    teamSize: { min: 1, max: 4 },
    themes: ['Web Development', 'Open Innovation'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devfolio.co',
    source: 'Devfolio',
  }),
  H({
    name: 'Solo Hack Weekend',
    organizer: 'Indie Hackers India',
    description: 'Solo-only hackathon. Ship your indie SaaS in 48 hours.',
    prizePool: 100000,
    registrationDeadline: daysFromNow(4),
    startDate: daysFromNow(11),
    endDate: daysFromNow(13),
    mode: 'online',
    location: 'Online',
    teamSize: { min: 1, max: 1 },
    themes: ['Web Development', 'AI', 'Mobile Development'],
    difficulty: 'Intermediate',
    registrationLink: 'https://devpost.com',
    source: 'Devpost',
    beginnerFriendly: true,
  }),
];
